function output = runSol(model)
    std1 = model.study.create('std1');
    std1.create('bma', 'BoundaryModeAnalysis');
    std1.create('freq', 'Frequency');
    std1.feature('bma').set('modeFreq', '1e9');
    std1.feature('bma').set('neigsactive', true);
    std1.feature('bma').set('shift', '0.9*ka');
    std1.feature('bma').set('shiftactive', true);
    std1.feature('bma').set('eigwhich', 'lr');
    std1.feature('freq').set('plist', '1e9');
    
    sol1 = model.sol.create('sol1');
    sol1.study('std1')
    sol1.attach('std1');
    sol1.create('st1', 'StudyStep');
    sol1.create('v1', 'Variables');
    sol1.create('e1', 'Eigenvalue');
    sol1.create('su1', 'StoreSolution');
    sol1.create('st2', 'StudyStep');
    sol1.create('v2', 'Variables');
    sol1.create('s1', 'Stationary');
    sol1.feature('s1').create('p1', 'Parametric');
    sol1.feature('s1').create('fc1', 'FullyCoupled');
    sol1.feature('s1').create('d1', 'Direct');
    sol1.feature('s1').create('i1', 'Iterative');
    sol1.feature('s1').create('pDef', 'Parametric');
    sol1.feature('s1').feature('i1').create('mg1', 'Multigrid');
    sol1.feature('s1').feature('i1').feature('mg1').feature('pr').create('so1', 'SOR');
    sol1.feature('s1').feature('i1').feature('mg1').feature('po').create('so1', 'SOR');
    sol1.feature('s1').feature('i1').feature('mg1').feature('cs').create('d1', 'Direct');
    
    %sol1.attach('std1');
    sol1.feature('st1').label('Compile Equations: Boundary Mode Analysis');
    sol1.feature('v1').label('Dependent Variables 1.1');
    sol1.feature('e1').label('Eigenvalue Solver 1.1');
    sol1.feature('e1').set('transform', 'outofplanewavenumber');
    sol1.feature('e1').set('neigs', 1);
    sol1.feature('e1').set('shift', '0.9*ka');
    sol1.feature('e1').set('eigwhich', 'si');
    sol1.feature('e1').feature('dDef').label('Direct 1');
    sol1.feature('e1').feature('aDef').label('Advanced 1');
    sol1.feature('e1').feature('aDef').set('cachepattern', true);
    sol1.feature('su1').label('Solution Store 1.1');
    sol1.feature('st2').label('Compile Equations: Frequency Domain');
    sol1.feature('st2').set('studystep', 'freq');
    sol1.feature('v2').label('Dependent Variables 2.1');
    sol1.feature('v2').set('initmethod', 'sol');
    sol1.feature('v2').set('initsol', 'sol1');
    sol1.feature('v2').set('solnum', 'auto');
    sol1.feature('v2').set('notsolmethod', 'sol');
    sol1.feature('v2').set('notsol', 'sol1');
    sol1.feature('v2').set('notsolnum', 'auto');
    sol1.feature('v2').set('clistctrl', {'pDef'});
    sol1.feature('v2').set('cname', {'freq'});
    sol1.feature('v2').set('clist', {'1e9[Hz]'});
    sol1.feature('s1').label('Stationary Solver 1.1');
    sol1.feature('s1').set('control', 'freq');
    sol1.feature('s1').set('probesel', 'none');
    sol1.feature('s1').feature('dDef').label('Direct 2');
    sol1.feature('s1').feature('fcDef').label('Fully Coupled 2');
    sol1.feature('s1').feature('aDef').label('Advanced 1');
    sol1.feature('s1').feature('aDef').set('cachepattern', true);
    sol1.feature('s1').feature('p1').label('Parametric 1.1');
    sol1.feature('s1').feature('p1').set('control', 'freq');
    sol1.feature('s1').feature('p1').set('pname', {'freq'});
    sol1.feature('s1').feature('p1').set('plistarr', {'1e9'});
    sol1.feature('s1').feature('p1').set('punit', {'Hz'});
    sol1.feature('s1').feature('p1').set('pcontinuationmode', 'no');
    sol1.feature('s1').feature('fc1').label('Fully Coupled 1.1');
    sol1.feature('s1').feature('fc1').set('linsolver', 'd1');
    sol1.feature('s1').feature('d1').label('Suggested Direct Solver (solid)');
    sol1.feature('s1').feature('d1').set('linsolver', 'pardiso');
    sol1.feature('s1').feature('d1').set('pivotperturb', 1.0E-9);
    sol1.feature('s1').feature('i1').label('Suggested Iterative Solver (solid)');
    sol1.feature('s1').feature('i1').set('nlinnormuse', true);
    sol1.feature('s1').feature('i1').feature('ilDef').label('Incomplete LU 1');
    sol1.feature('s1').feature('i1').feature('mg1').label('Multigrid 1.1');
    sol1.feature('s1').feature('i1').feature('mg1').feature('pr').label('Presmoother 1');
    sol1.feature('s1').feature('i1').feature('mg1').feature('pr').feature('soDef').label('SOR 2');
    sol1.feature('s1').feature('i1').feature('mg1').feature('pr').feature('so1').label('SOR 1.1');
    sol1.feature('s1').feature('i1').feature('mg1').feature('pr').feature('so1').set('relax', 0.8);
    sol1.feature('s1').feature('i1').feature('mg1').feature('po').label('Postsmoother 1');
    sol1.feature('s1').feature('i1').feature('mg1').feature('po').feature('soDef').label('SOR 2');
    sol1.feature('s1').feature('i1').feature('mg1').feature('po').feature('so1').label('SOR 1.1');
    sol1.feature('s1').feature('i1').feature('mg1').feature('po').feature('so1').set('relax', 0.8);
    sol1.feature('s1').feature('i1').feature('mg1').feature('cs').label('Coarse Solver 1');
    sol1.feature('s1').feature('i1').feature('mg1').feature('cs').feature('dDef').label('Direct 2');
    sol1.feature('s1').feature('i1').feature('mg1').feature('cs').feature('d1').label('Direct 1.1');
    sol1.feature('s1').feature('i1').feature('mg1').feature('cs').feature('d1').set('linsolver', 'pardiso');
    sol1.feature('s1').feature('i1').feature('mg1').feature('cs').feature('d1').set('pivotperturb', 1.0E-9);
    sol1.feature('s1').feature('pDef').label('Parametric 1');
    sol1.feature('s1').feature('pDef').set('control', 'freq');
    sol1.feature('s1').feature('pDef').set('pname', {'freq'});
    sol1.feature('s1').feature('pDef').set('plistarr', {'1e9'});
    sol1.feature('s1').feature('pDef').set('punit', {'Hz'});
    sol1.feature('s1').feature('pDef').set('pcontinuationmode', 'no');
    sol1.feature('s1').feature('pDef').set('uselsqdata', false);
    sol1.runAll;
    output = model;

end